[zh-cn]
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "Ceritor Hanio"
    weight            = 1

[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "Ceritor Hanio"
    weight            = 2
